name: Create envfile

on: [ push ]

jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        QE_BASE_URL: ${{ secrets.BASE_URL }}
        QE_BROWSER: ${{ secrets.BROWSER }}
        QE_API_SUFFIX: ${{ secrets.API_SUFFIX }}
        
