on: [ push ]
jobs: 
  create_env_file_job:
    runs-on: ubuntu-latest
    steps:
      - name: create env file
        run: |
         touch .env.qe
         echo BASE_URL=${{ secrets.QE_BASE_URL }} >> .env
