name: Create envfile

on: [ push ]

jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_SOME_API_KEY: ${{ secrets.BASE_URL }}
        envkey_SECRET_KEY: ${{ secrets.API_SUFFIX }}

name: Create envfile

on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load environment variables
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm install dotenv

      - name: Print environment variables
        env:
          BASE_URL: ${{ secrets.QE_BASE_URL }}
          API_SUFFIX: ${{ secrets.QE_API_SUFFIX }}
        run: |
          npx dotenv -e .env echo $BASE_URL
